version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: php:8.1-fpm
        container_name: php
        tty: true
        working_dir: /var/www
        restart: unless-stopped
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - ./:/var/www
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            app-net:
                ipv4_address: 172.10.0.6

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - ${APP_PORT}:80
        depends_on:
            - php
        links:
            - php
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
        networks:
            app-net:
                ipv4_address: 172.10.0.5
    postgres:
        image: postgres:13.3
        container_name: postgres
        environment:
            POSTGRES_DB: anime_list
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_PASSWORD}"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped
        networks:
            app-net:
                ipv4_address: 172.10.0.7

    adminer:
        image: adminer
        container_name: adminer
        depends_on:
            -   postgres
        links:
            -   postgres
        restart: always
        ports:
            - 8080:9000
        environment:
            ADMINER_DEFAULT_DB_DRIVER: pgsql
            ADMINER_DEFAULT_DB_HOST: postgres
            ADMINER_DEFAULT_DB_NAME: anime_list
            ADMINER_DESIGN: pepa-linha-dark
            ADMINER_PLUGINS: tables-filter tinymce
        networks:
            app-net:
                ipv4_address: 172.10.0.10

volumes:
    pgdata:
        driver: local

networks:
    app-net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.10.0.0/16
